# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d65fa8e6e67dcda578d840bc4535c47aab85721a1045c0d628edcb02b7b555a1b8f22e3cdaad02a2fe369e32fd0a7013e1de083caff4e012aa5627f95465ceee

test:
  secret_key_base: 3978cbea162a2ac1868c83edb316c71671745c8b832bafc8641b6500859fe313e78bcacce518375a920bfcb100499869e57ed1a8d4a1a277bbdec1a8f865ce54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
